In [12]:
import json
import sqlite3
import requests

# Step 1: Get the data (replace with actual API call or use the provided data)
url = "http://api.geonames.org/searchJSON?country=IN&featureClass=P&maxRows=100&username=srirampalika23"
response = requests.get(url)
data = response.json()

# Step 2: Connect to SQLite (or other database)
conn = sqlite3.connect('geonamesone.db')
cursor = conn.cursor()

# Step 3: Create the table to store city names and latitudes
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Geonames1 (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        lat REAL NOT NULL
    )
''')

# Step 4: Extract 'name' and 'lat' from the JSON data and insert into the table
for item in data['geonames']:
    name = item['name']
    lat = item['lat']
    
    cursor.execute('''
        INSERT INTO Geonames1 (name, lat)
        VALUES (?, ?)
    ''', (name, lat))
    print(name)
    print(lat)

# Step 5: Commit the transaction and close the connection
conn.commit()
conn.close()

print("Data has been inserted into the database.")

Delhi
28.65195
Mumbai
19.07283
Kolkata
22.56263
Hyderabad
17.38405
Bengaluru
12.97194
Chennai
13.08784
Ahmedabad
23.02579
New Delhi
28.62137
Pune
18.51957
Surat
21.19594
Dehradun
30.32443
Chandigarh
30.73629
Jaipur
26.91962
Bhubaneswar
20.27241
Bhopal
23.25469
Lucknow
26.83928
Kanpur
26.46523
Puducherry
11.93381
Patna
25.59408
Ranchi
23.34316
Raipur
21.23333
Thiruvananthapuram
8.4855
Srinagar
34.08565
Amritsar
31.62234
Durgapur
23.51583
Dhanbad
23.79759
Cuttack
20.46497
Coimbatore
11.00555
Ernakulam
9.93988
Jamshedpur
22.80278
Jammu
32.73528
Jalgaon
21.00292
Jabalpur
23.16697
Indore
22.71792
Imphal
24.80805
Howrah
22.57688
Kalaburgi
17.33583
Gorakhpur
26.76628
Guwahati
26.1844
Gandhinagar
23.21667
Faridabad
28.41124
Erode
11.3428
Bhiwandi
19.30023
Bhilai
21.20919
Bhavnagar
21.76287
Belagavi
15.85212
Bareilly
28.36678
Aurangabad
19.87757
Meerut
28.98002
Mangaluru
12.91723
Madurai
9.919
Ludhiana
30.91204
Kozhikode
11.24802
Kota
25.18254
Kohima
25.67467
Jalandhar
31.32556
Jodhpur
26.26841
Port Blair
11.66613
Panjim
15.49574
Nellore
14.44992
Nashik
19.99727
Nanded
19.16023
Nagpur
21.14631
Mysuru
12.29791
Shimla
31.10442
Solapur
17.67152
Shillong
25.56892
Salem
11.65376
Rourkela
22.22496
Rajkot
22.29161
Warangal
18
Visakhapatnam
17.68009
Vijayawada
16.50745
Varanasi
25.31668
Vadodara
22.29941
Ujjain
23.18239
Tirupur
11.11541
Tirunelveli
8.72742
Tiruchirappalli
10.8155
ThƒÅne
19.19704
Alwar
27.56246
Prayagraj
25.44478
Aligarh
27.88145
Ajmer
26.4521
Aizawl
23.72894
Agra
27.18333
Agartala
23.83605
Navi Mumbai
19.03681
Durg
21.19147
Dombivali
19.21667
Dispur
26.13564
Dindigul
10.36896
Dibrugarh
27.47989
Dewas
22.96585
Deoria
26.50167
Darjeeling
27.03333
Darbhanga
26.15216
Damoh
23.83312
Daman
20.41431
Cuddalore
11.75617
Data has been inserted into the database.

In [14]:
import json
import mysql.connector
import requests
from tabulate import tabulate
from flask import Flask, jsonify

app = Flask(__name__)

# Function to fetch data from the Geonames API and insert it into the MySQL database
def fetch_and_store_data():
    # Step 1: Fetch the JSON data from the API
    url = "http://api.geonames.org/searchJSON?country=IN&featureClass=P&maxRows=100&username=srirampalika23"
    response = requests.get(url)
    data = response.json()

    # Step 2: Connect to the MySQL database on port 3307
    conn = mysql.connector.connect(
        host='localhost',
        user='root',    # Replace with your MySQL username
        password='root', # Replace with your MySQL password
        database='geolocations', # Replace with your MySQL database name
        port=3307                 # Connect to port 3307
    )
    cursor = conn.cursor()

    # Step 3: Create the table if it doesn't exist
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Geonames (
            name VARCHAR(255) NOT NULL,
            lat DOUBLE NOT NULL
        )
    ''')

    # Step 4: Insert data into the table
    for city in data['geonames']:
        name = city['name']
        lat = float(city['lat'])  # Convert lat to float for MySQL
        sql = "INSERT INTO Geonames (name, lat) VALUES (%s, %s)"
        cursor.execute(sql, (name, lat))
    
    # Commit the transaction
    conn.commit()

    # Step 5: Close the connection
    cursor.close()
    conn.close()

@app.route('/geonames', methods=['GET'])
def get_geonames():
    # Connect to the MySQL database
    conn = mysql.connector.connect(
        host='localhost',
        user='root',    # Replace with your MySQL username
        password='root', # Replace with your MySQL password
        database='geolocations', # Replace with your MySQL database name
        port=3307                 # Connect to port 3307
    )
    cursor = conn.cursor()

    # Step 6: Query the data from the Geonames table
    cursor.execute('SELECT name, lat FROM Geonames')

    # Fetch all rows from the result
    rows = cursor.fetchall()

    # Step 7: Prepare the data for JSON response
    data = [{"name": row[0], "latitude": row[1]} for row in rows]

    # Close the connection
    cursor.close()
    conn.close()

    # Return the data as a JSON response
    return jsonify(data)

if __name__ == '__main__':
    fetch_and_store_data()  # Fetch and store data from the API on startup
    app.run(debug=True, port=5000)  # Runs the app on port 5000

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

 * Restarting with watchdog (windowsapi)

SystemExit: 1

In [15]:
import mysql.connector

try:
    conn = mysql.connector.connect(
        host='localhost',
        user='root',        # Replace with your MySQL username
        password='root',     # Replace with your MySQL password
        database='geolocations', # Replace with your MySQL database name
        port=3307            # Connect to port 3307
    )
    print("Connected to MySQL database.")
except mysql.connector.Error as err:
    print(f"Error: {err}")

Connected to MySQL database.

In [16]:
import mysql.connector
from tabulate import tabulate

# Step 1: Connect to the MySQL database on port 3307
conn = mysql.connector.connect(
    host='localhost',
    user='root',    # Replace with your MySQL username
    password='root', # Replace with your MySQL password
    database='geolocations', # Replace with your MySQL database name
    port=3307                 # Connect to port 3307
)
cursor = conn.cursor()

# Step 2: Create a table if it doesn't exist
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Geonames (
        name VARCHAR(255) NOT NULL,
        lat DOUBLE NOT NULL
    )
''')

# Step 3: Insert data into the table (Uncomment if you need to insert data)
# data = [
#     ("Delhi", 28.65195),
#     ("Mumbai", 19.07283),
#     ("Kolkata", 22.56263),
#     ("Hyderabad", 17.38405),
#     ("Bengaluru", 12.97194)
# ]
# cursor.executemany('INSERT INTO Geonames (name, lat) VALUES (%s, %s)', data)
# conn.commit()

# Step 4: Query the data from the Geonames table
cursor.execute('SELECT name, lat FROM Geonames')

# Fetch all rows from the result
rows = cursor.fetchall()

# Define the headers
headers = ["Name", "Latitude"]

# Format the latitudes to ensure they are displayed as raw values
formatted_rows = [(row[0], f"{row[1]}") for row in rows]

# Step 5: Display the data in a table format with borders
print("Data from MySQL on port 3307:")
print(tabulate(formatted_rows, headers, tablefmt="grid"))

# Step 6: Close the connection
conn.close()

Data from MySQL on port 3307:
+--------------------+------------+
| Name               |   Latitude |
+====================+============+
| Delhi              |   28.6519  |
+--------------------+------------+
| Mumbai             |   19.0728  |
+--------------------+------------+
| Kolkata            |   22.5626  |
+--------------------+------------+
| Hyderabad          |   17.384   |
+--------------------+------------+
| Bengaluru          |   12.9719  |
+--------------------+------------+
| Chennai            |   13.0878  |
+--------------------+------------+
| Ahmedabad          |   23.0258  |
+--------------------+------------+
| New Delhi          |   28.6214  |
+--------------------+------------+
| Pune               |   18.5196  |
+--------------------+------------+
| Surat              |   21.1959  |
+--------------------+------------+
| Dehradun           |   30.3244  |
+--------------------+------------+
| Chandigarh         |   30.7363  |
+--------------------+------------+
| Jaipur             |   26.9196  |
+--------------------+------------+
| Bhubaneswar        |   20.2724  |
+--------------------+------------+
| Bhopal             |   23.2547  |
+--------------------+------------+
| Lucknow            |   26.8393  |
+--------------------+------------+
| Kanpur             |   26.4652  |
+--------------------+------------+
| Puducherry         |   11.9338  |
+--------------------+------------+
| Patna              |   25.5941  |
+--------------------+------------+
| Ranchi             |   23.3432  |
+--------------------+------------+
| Raipur             |   21.2333  |
+--------------------+------------+
| Thiruvananthapuram |    8.4855  |
+--------------------+------------+
| Srinagar           |   34.0857  |
+--------------------+------------+
| Amritsar           |   31.6223  |
+--------------------+------------+
| Durgapur           |   23.5158  |
+--------------------+------------+
| Dhanbad            |   23.7976  |
+--------------------+------------+
| Cuttack            |   20.465   |
+--------------------+------------+
| Coimbatore         |   11.0055  |
+--------------------+------------+
| Ernakulam          |    9.93988 |
+--------------------+------------+
| Jamshedpur         |   22.8028  |
+--------------------+------------+
| Jammu              |   32.7353  |
+--------------------+------------+
| Jalgaon            |   21.0029  |
+--------------------+------------+
| Jabalpur           |   23.167   |
+--------------------+------------+
| Indore             |   22.7179  |
+--------------------+------------+
| Imphal             |   24.8081  |
+--------------------+------------+
| Howrah             |   22.5769  |
+--------------------+------------+
| Kalaburgi          |   17.3358  |
+--------------------+------------+
| Gorakhpur          |   26.7663  |
+--------------------+------------+
| Guwahati           |   26.1844  |
+--------------------+------------+
| Gandhinagar        |   23.2167  |
+--------------------+------------+
| Faridabad          |   28.4112  |
+--------------------+------------+
| Erode              |   11.3428  |
+--------------------+------------+
| Bhiwandi           |   19.3002  |
+--------------------+------------+
| Bhilai             |   21.2092  |
+--------------------+------------+
| Bhavnagar          |   21.7629  |
+--------------------+------------+
| Belagavi           |   15.8521  |
+--------------------+------------+
| Bareilly           |   28.3668  |
+--------------------+------------+
| Aurangabad         |   19.8776  |
+--------------------+------------+
| Meerut             |   28.98    |
+--------------------+------------+
| Mangaluru          |   12.9172  |
+--------------------+------------+
| Madurai            |    9.919   |
+--------------------+------------+
| Ludhiana           |   30.912   |
+--------------------+------------+
| Kozhikode          |   11.248   |
+--------------------+------------+
| Kota               |   25.1825  |
+--------------------+------------+
| Kohima             |   25.6747  |
+--------------------+------------+
| Jalandhar          |   31.3256  |
+--------------------+------------+
| Jodhpur            |   26.2684  |
+--------------------+------------+
| Port Blair         |   11.6661  |
+--------------------+------------+
| Panjim             |   15.4957  |
+--------------------+------------+
| Nellore            |   14.4499  |
+--------------------+------------+
| Nashik             |   19.9973  |
+--------------------+------------+
| Nanded             |   19.1602  |
+--------------------+------------+
| Nagpur             |   21.1463  |
+--------------------+------------+
| Mysuru             |   12.2979  |
+--------------------+------------+
| Shimla             |   31.1044  |
+--------------------+------------+
| Solapur            |   17.6715  |
+--------------------+------------+
| Shillong           |   25.5689  |
+--------------------+------------+
| Salem              |   11.6538  |
+--------------------+------------+
| Rourkela           |   22.225   |
+--------------------+------------+
| Rajkot             |   22.2916  |
+--------------------+------------+
| Warangal           |   18       |
+--------------------+------------+
| Visakhapatnam      |   17.6801  |
+--------------------+------------+
| Vijayawada         |   16.5074  |
+--------------------+------------+
| Varanasi           |   25.3167  |
+--------------------+------------+
| Vadodara           |   22.2994  |
+--------------------+------------+
| Ujjain             |   23.1824  |
+--------------------+------------+
| Tirupur            |   11.1154  |
+--------------------+------------+
| Tirunelveli        |    8.72742 |
+--------------------+------------+
| Tiruchirappalli    |   10.8155  |
+--------------------+------------+
| ThƒÅne              |   19.197   |
+--------------------+------------+
| Alwar              |   27.5625  |
+--------------------+------------+
| Prayagraj          |   25.4448  |
+--------------------+------------+
| Aligarh            |   27.8815  |
+--------------------+------------+
| Ajmer              |   26.4521  |
+--------------------+------------+
| Aizawl             |   23.7289  |
+--------------------+------------+
| Agra               |   27.1833  |
+--------------------+------------+
| Agartala           |   23.8361  |
+--------------------+------------+
| Navi Mumbai        |   19.0368  |
+--------------------+------------+
| Durg               |   21.1915  |
+--------------------+------------+
| Dombivali          |   19.2167  |
+--------------------+------------+
| Dispur             |   26.1356  |
+--------------------+------------+
| Dindigul           |   10.369   |
+--------------------+------------+
| Dibrugarh          |   27.4799  |
+--------------------+------------+
| Dewas              |   22.9658  |
+--------------------+------------+
| Deoria             |   26.5017  |
+--------------------+------------+
| Darjeeling         |   27.0333  |
+--------------------+------------+
| Darbhanga          |   26.1522  |
+--------------------+------------+
| Damoh              |   23.8331  |
+--------------------+------------+
| Daman              |   20.4143  |
+--------------------+------------+
| Cuddalore          |   11.7562  |
+--------------------+------------+
| Delhi              |   28.6519  |
+--------------------+------------+
| Mumbai             |   19.0728  |
+--------------------+------------+
| Kolkata            |   22.5626  |
+--------------------+------------+
| Hyderabad          |   17.384   |
+--------------------+------------+
| Bengaluru          |   12.9719  |
+--------------------+------------+
| Chennai            |   13.0878  |
+--------------------+------------+
| Ahmedabad          |   23.0258  |
+--------------------+------------+
| New Delhi          |   28.6214  |
+--------------------+------------+
| Pune               |   18.5196  |
+--------------------+------------+
| Surat              |   21.1959  |
+--------------------+------------+
| Dehradun           |   30.3244  |
+--------------------+------------+
| Chandigarh         |   30.7363  |
+--------------------+------------+
| Jaipur             |   26.9196  |
+--------------------+------------+
| Bhubaneswar        |   20.2724  |
+--------------------+------------+
| Bhopal             |   23.2547  |
+--------------------+------------+
| Lucknow            |   26.8393  |
+--------------------+------------+
| Kanpur             |   26.4652  |
+--------------------+------------+
| Puducherry         |   11.9338  |
+--------------------+------------+
| Patna              |   25.5941  |
+--------------------+------------+
| Ranchi             |   23.3432  |
+--------------------+------------+
| Raipur             |   21.2333  |
+--------------------+------------+
| Thiruvananthapuram |    8.4855  |
+--------------------+------------+
| Srinagar           |   34.0857  |
+--------------------+------------+
| Amritsar           |   31.6223  |
+--------------------+------------+
| Durgapur           |   23.5158  |
+--------------------+------------+
| Dhanbad            |   23.7976  |
+--------------------+------------+
| Cuttack            |   20.465   |
+--------------------+------------+
| Coimbatore         |   11.0055  |
+--------------------+------------+
| Ernakulam          |    9.93988 |
+--------------------+------------+
| Jamshedpur         |   22.8028  |
+--------------------+------------+
| Jammu              |   32.7353  |
+--------------------+------------+
| Jalgaon            |   21.0029  |
+--------------------+------------+
| Jabalpur           |   23.167   |
+--------------------+------------+
| Indore             |   22.7179  |
+--------------------+------------+
| Imphal             |   24.8081  |
+--------------------+------------+
| Howrah             |   22.5769  |
+--------------------+------------+
| Kalaburgi          |   17.3358  |
+--------------------+------------+
| Gorakhpur          |   26.7663  |
+--------------------+------------+
| Guwahati           |   26.1844  |
+--------------------+------------+
| Gandhinagar        |   23.2167  |
+--------------------+------------+
| Faridabad          |   28.4112  |
+--------------------+------------+
| Erode              |   11.3428  |
+--------------------+------------+
| Bhiwandi           |   19.3002  |
+--------------------+------------+
| Bhilai             |   21.2092  |
+--------------------+------------+
| Bhavnagar          |   21.7629  |
+--------------------+------------+
| Belagavi           |   15.8521  |
+--------------------+------------+
| Bareilly           |   28.3668  |
+--------------------+------------+
| Aurangabad         |   19.8776  |
+--------------------+------------+
| Meerut             |   28.98    |
+--------------------+------------+
| Mangaluru          |   12.9172  |
+--------------------+------------+
| Madurai            |    9.919   |
+--------------------+------------+
| Ludhiana           |   30.912   |
+--------------------+------------+
| Kozhikode          |   11.248   |
+--------------------+------------+
| Kota               |   25.1825  |
+--------------------+------------+
| Kohima             |   25.6747  |
+--------------------+------------+
| Jalandhar          |   31.3256  |
+--------------------+------------+
| Jodhpur            |   26.2684  |
+--------------------+------------+
| Port Blair         |   11.6661  |
+--------------------+------------+
| Panjim             |   15.4957  |
+--------------------+------------+
| Nellore            |   14.4499  |
+--------------------+------------+
| Nashik             |   19.9973  |
+--------------------+------------+
| Nanded             |   19.1602  |
+--------------------+------------+
| Nagpur             |   21.1463  |
+--------------------+------------+
| Mysuru             |   12.2979  |
+--------------------+------------+
| Shimla             |   31.1044  |
+--------------------+------------+
| Solapur            |   17.6715  |
+--------------------+------------+
| Shillong           |   25.5689  |
+--------------------+------------+
| Salem              |   11.6538  |
+--------------------+------------+
| Rourkela           |   22.225   |
+--------------------+------------+
| Rajkot             |   22.2916  |
+--------------------+------------+
| Warangal           |   18       |
+--------------------+------------+
| Visakhapatnam      |   17.6801  |
+--------------------+------------+
| Vijayawada         |   16.5074  |
+--------------------+------------+
| Varanasi           |   25.3167  |
+--------------------+------------+
| Vadodara           |   22.2994  |
+--------------------+------------+
| Ujjain             |   23.1824  |
+--------------------+------------+
| Tirupur            |   11.1154  |
+--------------------+------------+
| Tirunelveli        |    8.72742 |
+--------------------+------------+
| Tiruchirappalli    |   10.8155  |
+--------------------+------------+
| ThƒÅne              |   19.197   |
+--------------------+------------+
| Alwar              |   27.5625  |
+--------------------+------------+
| Prayagraj          |   25.4448  |
+--------------------+------------+
| Aligarh            |   27.8815  |
+--------------------+------------+
| Ajmer              |   26.4521  |
+--------------------+------------+
| Aizawl             |   23.7289  |
+--------------------+------------+
| Agra               |   27.1833  |
+--------------------+------------+
| Agartala           |   23.8361  |
+--------------------+------------+
| Navi Mumbai        |   19.0368  |
+--------------------+------------+
| Durg               |   21.1915  |
+--------------------+------------+
| Dombivali          |   19.2167  |
+--------------------+------------+
| Dispur             |   26.1356  |
+--------------------+------------+
| Dindigul           |   10.369   |
+--------------------+------------+
| Dibrugarh          |   27.4799  |
+--------------------+------------+
| Dewas              |   22.9658  |
+--------------------+------------+
| Deoria             |   26.5017  |
+--------------------+------------+
| Darjeeling         |   27.0333  |
+--------------------+------------+
| Darbhanga          |   26.1522  |
+--------------------+------------+
| Damoh              |   23.8331  |
+--------------------+------------+
| Daman              |   20.4143  |
+--------------------+------------+
| Cuddalore          |   11.7562  |
+--------------------+------------+
| Delhi              |   28.6519  |
+--------------------+------------+
| Mumbai             |   19.0728  |
+--------------------+------------+
| Kolkata            |   22.5626  |
+--------------------+------------+
| Hyderabad          |   17.384   |
+--------------------+------------+
| Bengaluru          |   12.9719  |
+--------------------+------------+
| Chennai            |   13.0878  |
+--------------------+------------+
| Ahmedabad          |   23.0258  |
+--------------------+------------+
| New Delhi          |   28.6214  |
+--------------------+------------+
| Pune               |   18.5196  |
+--------------------+------------+
| Surat              |   21.1959  |
+--------------------+------------+
| Dehradun           |   30.3244  |
+--------------------+------------+
| Chandigarh         |   30.7363  |
+--------------------+------------+
| Jaipur             |   26.9196  |
+--------------------+------------+
| Bhubaneswar        |   20.2724  |
+--------------------+------------+
| Bhopal             |   23.2547  |
+--------------------+------------+
| Lucknow            |   26.8393  |
+--------------------+------------+
| Kanpur             |   26.4652  |
+--------------------+------------+
| Puducherry         |   11.9338  |
+--------------------+------------+
| Patna              |   25.5941  |
+--------------------+------------+
| Ranchi             |   23.3432  |
+--------------------+------------+
| Raipur             |   21.2333  |
+--------------------+------------+
| Thiruvananthapuram |    8.4855  |
+--------------------+------------+
| Srinagar           |   34.0857  |
+--------------------+------------+
| Amritsar           |   31.6223  |
+--------------------+------------+
| Durgapur           |   23.5158  |
+--------------------+------------+
| Dhanbad            |   23.7976  |
+--------------------+------------+
| Cuttack            |   20.465   |
+--------------------+------------+
| Coimbatore         |   11.0055  |
+--------------------+------------+
| Ernakulam          |    9.93988 |
+--------------------+------------+
| Jamshedpur         |   22.8028  |
+--------------------+------------+
| Jammu              |   32.7353  |
+--------------------+------------+
| Jalgaon            |   21.0029  |
+--------------------+------------+
| Jabalpur           |   23.167   |
+--------------------+------------+
| Indore             |   22.7179  |
+--------------------+------------+
| Imphal             |   24.8081  |
+--------------------+------------+
| Howrah             |   22.5769  |
+--------------------+------------+
| Kalaburgi          |   17.3358  |
+--------------------+------------+
| Gorakhpur          |   26.7663  |
+--------------------+------------+
| Guwahati           |   26.1844  |
+--------------------+------------+
| Gandhinagar        |   23.2167  |
+--------------------+------------+
| Faridabad          |   28.4112  |
+--------------------+------------+
| Erode              |   11.3428  |
+--------------------+------------+
| Bhiwandi           |   19.3002  |
+--------------------+------------+
| Bhilai             |   21.2092  |
+--------------------+------------+
| Bhavnagar          |   21.7629  |
+--------------------+------------+
| Belagavi           |   15.8521  |
+--------------------+------------+
| Bareilly           |   28.3668  |
+--------------------+------------+
| Aurangabad         |   19.8776  |
+--------------------+------------+
| Meerut             |   28.98    |
+--------------------+------------+
| Mangaluru          |   12.9172  |
+--------------------+------------+
| Madurai            |    9.919   |
+--------------------+------------+
| Ludhiana           |   30.912   |
+--------------------+------------+
| Kozhikode          |   11.248   |
+--------------------+------------+
| Kota               |   25.1825  |
+--------------------+------------+
| Kohima             |   25.6747  |
+--------------------+------------+
| Jalandhar          |   31.3256  |
+--------------------+------------+
| Jodhpur            |   26.2684  |
+--------------------+------------+
| Port Blair         |   11.6661  |
+--------------------+------------+
| Panjim             |   15.4957  |
+--------------------+------------+
| Nellore            |   14.4499  |
+--------------------+------------+
| Nashik             |   19.9973  |
+--------------------+------------+
| Nanded             |   19.1602  |
+--------------------+------------+
| Nagpur             |   21.1463  |
+--------------------+------------+
| Mysuru             |   12.2979  |
+--------------------+------------+
| Shimla             |   31.1044  |
+--------------------+------------+
| Solapur            |   17.6715  |
+--------------------+------------+
| Shillong           |   25.5689  |
+--------------------+------------+
| Salem              |   11.6538  |
+--------------------+------------+
| Rourkela           |   22.225   |
+--------------------+------------+
| Rajkot             |   22.2916  |
+--------------------+------------+
| Warangal           |   18       |
+--------------------+------------+
| Visakhapatnam      |   17.6801  |
+--------------------+------------+
| Vijayawada         |   16.5074  |
+--------------------+------------+
| Varanasi           |   25.3167  |
+--------------------+------------+
| Vadodara           |   22.2994  |
+--------------------+------------+
| Ujjain             |   23.1824  |